### ISSUE TITLE
Wuwa Mod

### ISSUE THREAD

**Issue by fairyilv** [saefulbarkah/CustomTP-wuwa#1]
Where is you Wuthering Waves Mod, why u delete it, it was a good mod

**Comment by saefulbarkah** [comment]
https://github.com/saefulbarkah/Maung-WW-Releases

**Comment by fairyilv** [comment]
> https://github.com/saefulbarkah/Maung-WW-Releases

Thx :)

**Comment by Verbinmay** [comment]
Why u delete it again, it was the best mod,  <3
